server:
  port: 8591
websocket:
  netty:
    port: 8581
    path: /websocket

# 线程池配置
#thread:
#  pool:
#    executor:
#      config:
#        core-pool-size: 20
#        max-pool-size: 50
#        keep-alive-time: 5000
#        block-queue-size: 5000
#        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: yxb
    password: iPDz5tLYpsXR5zzM
    url: jdbc:mysql://127.0.0.1:3306/yxb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1       # Redis服务器地址
    port: 6379            # 端口
    password: ruanjian123 # 密码（没有则省略）
    database: 0           # 数据库索引（0-15）
    timeout: 3000         # 连接超时（毫秒）
#  hikari:
#    pool-name: Retail_HikariCP
#    minimum-idle: 15 #最小空闲连接数量
#    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
#    maximum-pool-size: 25 #连接池最大连接数，默认是10
#    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
#    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
#    connection-test-query: SELECT 1
#  type: com.zaxxer.hikari.HikariDataSource

# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml
dubbo:
  application:
    name: post-consumer
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    parameters:
      namespace: public
  consumer:
    check: false # 启动时不检查提供者是否可用
    timeout: 30000
    retries: 0   # 快速失败
  protocol:
    name: dubbo
    port: 20880

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
# 日志
logging:
  level:
    root: debug
#  config: classpath:logback-spring.xml