server:
  port: 8791

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: yxb
    password: iPDz5tLYpsXR5zzM
    url: jdbc:mysql://127.0.0.1:3306/yxb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1       # Redis服务器地址
    port: 6379            # 端口
    password: ruanjian123 # 密码（没有则省略）
    database: 0           # 数据库索引（0-15）
    timeout: 3000         # 连接超时（毫秒）

dubbo:
  application:
    name: post-consumer
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    parameters:
      namespace: public
  consumer:
    check: false # 启动时不检查提供者是否可用
    timeout: 30000
    retries: 0   # 快速失败
  protocol:
    name: dubbo
    port: 20880

#dubbo:
#  application:
#    name: post-service-provider
#  registry:
#    address: nacos://127.0.0.1:8848
#    username: nacos
#    password: nacos
#  protocol:
#    name: dubbo
#    port: 20880
#  monitor:
#    protocol: registry
# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
# 日志
logging:
  level:
    root: info
    org.apache.dubbo: DEBUG
#  config: classpath:logback-spring.xml

